### ISSUE TITLE
Problem on Mac OSX 10.14 Mojave (java related ? )

### ISSUE THREAD

**Issue by wphantom** [adrian/upm-swing#53]
I just moved to Osx Mojave (10.14). 
When launching UPM it ask for installing java for mac... I did it (it is the same after all osx upgrades).

But now, UPM starts I have the main windows and the Master password windows but no controls are displayed in the windows : no text, no button, no text field. However it seems : i cant type my main password (the textfield is selected by default on startup) and it accept it but the main windows remain empty.... if I hit enter it open the window to the the selected account info but still empty...

It probably have to see with Java on mojave but can't find a tweak and I can't think of another java app on my system that works perfectly...

**Comment by michaelkit** [comment]
Same for me after the MacOS upgrade few days ago.
I'll glad to find solution.

**Comment by quincy-me** [comment]
Same for me. The now not so universal password manager. I've had to revert to running it in a virt to get around this issue. Highly annoying.

**Comment by N3WWN** [comment]
I started having an issue with the Mac OS X Mojave update, too.  Was working perfectly with High Sierra.

I reinstalled Java (https://support.apple.com/kb/DL1572?viewlocale=en_US&locale=en_US) as well as UPM itself.

I don't even get the Master password window on my system.  I have UPM docked and the icon grows and shrinks, but never displays anything and doesn't show the "running dot" under the icon after attempting launch.

Attempting to launch from the command line, the error I'm getting is:

> $ open -a UPM
LSOpenURLsWithRole() failed for the application /Applications/UPM.app with error -10810.

I use UPM to safely store a lot of information and my only non-phone devices are Mac OS X, so I'd really like to see this fixed. ;)

Let me know if there's any additional information that I can provide to assist in troubleshooting and resolving this issue.

Thanks!

**Comment by michaelkit** [comment]
The problem was resolved in the one of last updates.

**Comment by N3WWN** [comment]
Thanks for resolving this issue!  I had to completely remove UPM from my Applications folder and re-add it, but UPM is back up and running for me! 

Cheers! 🥂

**Comment by adrian** [comment]
Fixed in release v1.15.1.
